# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: spedn
version: '0.0.0'
github: "githubuser/spedn"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: spedn is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - megaparsec
  - mtl
  - containers
  source-dirs: library

executables:
  spedn:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - spedn
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

benchmarks:
  spedn-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - spedn
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  spedn-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - spedn
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
